# Generated by Django 4.1.4 on 2024-11-23 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Abstract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("coresponding_author_fullname", models.CharField(max_length=200)),
                ("coresponding_author_email", models.EmailField(max_length=140)),
                ("coresponding_author_phone", models.CharField(max_length=140)),
                (
                    "abstract_document_file",
                    models.FileField(max_length=500, upload_to="uploads/"),
                ),
                (
                    "presentation_type",
                    models.CharField(
                        choices=[
                            ("oral", "Live oral"),
                            ("virtual", "Live Virtual"),
                            ("poster", "Poster"),
                        ],
                        max_length=100,
                    ),
                ),
                ("research_area", models.CharField(max_length=200)),
                ("keywords", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClearanceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submission_type",
                    models.CharField(
                        choices=[
                            ("Manuscript", "Manuscript"),
                            ("Exhibition", "Exhibition"),
                            ("Advert", "Advert"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "submission_file",
                    models.FileField(max_length=500, null=True, upload_to="uploads/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Pending verification"),
                            (1, "Verified"),
                            (2, "Failed verification"),
                        ],
                        default=0,
                    ),
                ),
                ("payment_proff", models.FileField(upload_to="uploads/receipts/")),
                ("failure_reason", models.CharField(blank=True, max_length=200)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReceiptVerificationLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=200)),
                (
                    "payment_bank",
                    models.CharField(
                        choices=[
                            ("OTHER", "BANK NOT LISTED"),
                            ("9_PAYMENT_SOLUTIONS_BANK", "9 PAYMENT SOLUTIONS BANK"),
                            ("AB_MICROFINANCE_BANK", "AB MICROFINANCE BANK"),
                            ("ABBEY_MORTGAGE_BANK", "ABBEY MORTGAGE BANK"),
                            (
                                "ABOVE_ONLY_MICROFINANCE_BANK",
                                "ABOVE ONLY MICROFINANCE BANK",
                            ),
                            ("ABU_MICROFINANCE_BANK", "ABU MICROFINANCE BANK"),
                            ("ACCESS_BANK", "Access bank"),
                            ("ACCESS_MONEY", "ACCESS MONEY"),
                            ("ACCESS_YELLO_BETA", "ACCESS YELLO & BETA"),
                            ("ACCION_MICROFINANCE_BANK", "ACCION MICROFINANCE BANK"),
                            (
                                "ADDOSSER_MICROFINANCE_BANK",
                                "ADDOSSER MICROFINANCE BANK",
                            ),
                            (
                                "ADEYEMI_COLLEGE_STAFF_MICROFINANCE_BANK",
                                "ADEYEMI COLLEGE STAFF MICROFINANCE BANK",
                            ),
                            (
                                "AFEKHAFE_MICROFINANCE_BANK",
                                "AFEKHAFE MICROFINANCE BANK",
                            ),
                            ("AG_MORTGAGE_BANK", "AG MORTGAGE BANK"),
                            (
                                "AL_BARAKAH_MICROFINANCE_BANK",
                                "AL-BARAKAH MICROFINANCE BANK",
                            ),
                            ("ALEKUN_MICROFINANCE_BANK", "ALEKUN MICROFINANCE BANK"),
                            ("ALERT_MICROFINANCE_BANK", "ALERT MICROFINANCE BANK"),
                            (
                                "ALLWORKERS_MICROFINANCE_BANK",
                                "ALLWORKERS MICROFINANCE BANK",
                            ),
                            (
                                "ALPHA_KAPITAL_MICROFINANCE_BANK",
                                "ALPHA KAPITAL MICROFINANCE BANK",
                            ),
                            ("AMML_MICROFINANCE_BANK", "AMML MICROFINANCE BANK"),
                            ("APEKS_MICROFINANCE_BANK", "APEKS MICROFINANCE BANK"),
                            ("ARISE_MICROFINANCE_BANK", "ARISE MICROFINANCE BANK"),
                            ("ASO_SAVINGS", "ASO SAVINGS"),
                            (
                                "ASSETMATRIX_MICROFINANCE_BANK",
                                "ASSETMATRIX MICROFINANCE BANK",
                            ),
                            (
                                "ASTRAPOLARIS_MICROFINANCE_BANK",
                                "ASTRAPOLARIS MICROFINANCE BANK",
                            ),
                            ("AUCHI_MICROFINANCE_BANK", "AUCHI MICROFINANCE BANK"),
                            (
                                "BAINES_CREDIT_MICROFINANCE_BANK",
                                "BAINES CREDIT MICROFINANCE BANK",
                            ),
                            (
                                "BALOGUN_GAMBARI_MICROFINANCE_BANK",
                                "BALOGUN GAMBARI MICROFINANCE BANK",
                            ),
                            ("BC_KASH_MICROFINANCE_BANK", "BC KASH MICROFINANCE BANK"),
                            ("BIPC_MICROFINANCE_BANK", "BIPC MICROFINANCE BANK"),
                            (
                                "BOCTRUST_MICROFINANCE_BANK_LIMITED",
                                "BOCTRUST MICROFINANCE BANK LIMITED",
                            ),
                            ("BOSAK_MICROFINANCE_BANK", "BOSAK MICROFINANCE BANK"),
                            ("BOWEN_MICROFINANCE_BANK", "Bowen Microfinance Bank"),
                            ("BRENT_MORTGAGE_BANK", "BRENT MORTGAGE BANK"),
                            (
                                "BRIGHTWAY_MICROFINANCE_BANK",
                                "BRIGHTWAY MICROFINANCE BANK",
                            ),
                            (
                                "CASHCONNECT_MICROFINANCE_BANK",
                                "CASHCONNECT MICROFINANCE BANK",
                            ),
                            ("CELLULANT", "CELLULANT"),
                            ("CEMCS_MICROFINANCE_BANK", "CEMCS Microfinance Bank"),
                            ("CHAMS_MOBILE", "CHAMS MOBILE"),
                            ("CHIKUM_MICROFINANCE_BANK", "CHIKUM MICROFINANCE BANK"),
                            ("CIT_MICROFINANCE_BANK", "CIT MICROFINANCE BANK"),
                            ("CITIBANK_NIGERIA", "Citibank Nigeria"),
                            (
                                "COASTLINE_MICROFINANCE_BANK",
                                "COASTLINE MICROFINANCE BANK",
                            ),
                            ("CONPRO_MICROFINANCE_BANK", "CONPRO MICROFINANCE BANK"),
                            (
                                "CONSUMER_MICROFINANCE_BANK",
                                "CONSUMER MICROFINANCE BANK",
                            ),
                            (
                                "CONTEC_GLOBAL_INFOTECH_LIMITED",
                                "CONTEC GLOBAL INFOTECH LIMITED(NOWNOW)",
                            ),
                            (
                                "CORESTEP_MICROFINANCE_BANK",
                                "CORESTEP MICROFINANCE BANK",
                            ),
                            ("CORONATION_BANK", "Coronation Bank"),
                            ("COVENANT_MFB", "COVENANT MFB"),
                            (
                                "CREDIT_AFRIQUE_MICROFINANCE_BANK",
                                "CREDIT AFRIQUE MICROFINANCE BANK",
                            ),
                            (
                                "DAVODANI_MICROFINANCE_BANK",
                                "DAVODANI  MICROFINANCE BANK",
                            ),
                            (
                                "DAYLIGHT_MICROFINANCE_BANK",
                                "DAYLIGHT MICROFINANCE BANK",
                            ),
                            ("DIAMOND_BANK", "Diamond bank"),
                            ("E_BARCS_MICROFINANCE_BANK", "E-BARCS MICROFINANCE BANK"),
                            (
                                "EAGLE_FLIGHT_MICROFINANCE_BANK",
                                "EAGLE FLIGHT MICROFINANCE BANK",
                            ),
                            ("EARTHOLEUM", "EARTHOLEUM"),
                            ("ECOBANK_NIGERIA_PLC", "Ecobank Nigeria Plc"),
                            ("ECOBANK_XPRESS_ACCOUNT", "ECOBANK XPRESS ACCOUNT"),
                            ("ECOMOBILE", "ECOMOBILE"),
                            (
                                "EK_RELIABLE_MICROFINANCE_BANK",
                                "EK-RELIABLE MICROFINANCE BANK",
                            ),
                            ("EKONDO_MICROFINANCE_BANK", "EKONDO MICROFINANCE BANK"),
                            ("EMERALD_MICROFINANCE_BANK", "EMERALD MICROFINANCE BANK"),
                            (
                                "EMPIRE_TRUST_MICROFINANCE_BANK",
                                "EMPIRE TRUST MICROFINANCE BANK",
                            ),
                            ("ENTERPRISE_BANK", "ENTERPRISE BANK"),
                            ("ESO_E_MICROFINANCE_BANK", "ESO-E MICROFINANCE BANK"),
                            ("ETRANZACT", "eTRANZACT"),
                            ("EVANGEL_MICROFINANCE_BANK", "EVANGEL MICROFINANCE BANK"),
                            (
                                "EVERGREEN_MICROFINANCE_BANK",
                                "EVERGREEN MICROFINANCE BANK",
                            ),
                            ("EYOWO", "Eyowo"),
                            ("FAST_MICROFINANCE_BANK", "FAST MICROFINANCE BANK"),
                            ("FBNQUEST_MERCHANT_BANK", "FBNQUEST MERCHANT BANK"),
                            ("FCMB_MOBILE", "FCMB MOBILE"),
                            ("FCT_MICROFINANCE_BANK", "FCT MICROFINANCE BANK"),
                            (
                                "FEDPOLY_NASARAWA_MICROFINANCE_BANK",
                                "FEDPOLY NASARAWA MICROFINANCE BANK",
                            ),
                            ("FETS", "FETS"),
                            ("FFS_MICROFINANCE_BANK", "FFS MICROFINANCE BANK"),
                            ("FIDELITY_BANK", "Fidelity bank"),
                            ("FIDELITY_MOBILE", "FIDELITY MOBILE"),
                            ("FIDFUND_MICROFINANCE_BANK", "FIDFUND MICROFINANCE Bank"),
                            (
                                "FINATRUST_MICROFINANCE_BANK",
                                "FINATRUST MICROFINANCE BANK",
                            ),
                            ("FINCA_MICROFINANCE_BANK", "FINCA MICROFINANCE BANK"),
                            ("FIRMUS_MICROFINANCE_BANK", "FIRMUS MICROFINANCE BANK"),
                            ("FIRST_BANK", "First bank"),
                            (
                                "FIRST_CITY_MONUMENT_BANK_PLC",
                                "First City Monument Bank Plc",
                            ),
                            (
                                "FIRST_GENERATION_MORTGAGE_BANK",
                                "FIRST GENERATION MORTGAGE BANK",
                            ),
                            (
                                "FIRST_OPTION_MICROFINANCE_BANK",
                                "FIRST OPTION MICROFINANCE BANK",
                            ),
                            (
                                "FIRST_TRUST_MORTGAGE_BANK_PLC",
                                "FIRST TRUST MORTGAGE BANK PLC",
                            ),
                            ("FIRSTMONIE_WALLET", "FIRSTMONIE WALLET"),
                            (
                                "FLUTTERWAVE_TECHNOLOGY_SOLUTIONS_LIMITED",
                                "FLUTTERWAVE TECHNOLOGY SOLUTIONS LIMITED",
                            ),
                            ("FORTIS_MICROFINANCE_BANK", "FORTIS MICROFINANCE BANK"),
                            ("FORTIS_MOBILE", "FORTIS MOBILE"),
                            ("FSDH", "FSDH"),
                            (
                                "FULLRANGE_MICROFINANCE_BANK",
                                "FULLRANGE MICROFINANCE BANK",
                            ),
                            ("FUTO_MICROFINANCE_BANK", "FUTO MICROFINANCE BANK"),
                            ("GATEWAY_MORTGAGE_BANK", "GATEWAY MORTGAGE BANK"),
                            ("GLOBUS_BANK", "Globus Bank"),
                            ("GLORY_MICROFINANCE_BANK", "GLORY MICROFINANCE BANK"),
                            ("GOWANS_MICROFINANCE_BANK", "GOWANS MICROFINANCE BANK"),
                            (
                                "GREENBANK_MICROFINANCE_BANK",
                                "GREENBANK MICROFINANCE BANK",
                            ),
                            (
                                "GROOMING_MICROFINANCE_BANK",
                                "GROOMING MICROFINANCE BANK",
                            ),
                            ("GT_MOBILE", "GT MOBILE"),
                            ("GTBANK", "GTBank"),
                            ("GTI_MICROFINANCE_BANK", "GTI MICROFINANCE BANK"),
                            ("HACKMAN_MICROFINANCE_BANK", "Hackman Microfinance Bank"),
                            (
                                "HAGGAI_MORTGAGE_BANK_LIMITED",
                                "HAGGAI MORTGAGE BANK LIMITED",
                            ),
                            ("HASAL_MICROFINANCE_BANK", "Hasal Microfinance Bank"),
                            ("HEADWAY_MICROFINANCE_BANK", "HEADWAY MICROFINANCE BANK"),
                            ("HEDONMARK", "HEDONMARK"),
                            ("HERITAGE_BANK", "Heritage bank"),
                            ("IBILE_MICROFINANCE_BANK", "Ibile Microfinance Bank"),
                            ("IKENNE_MICROFINANCE_BANK", "IKENNE MICROFINANCE BANK"),
                            ("IKIRE_MICROFINANCE_BANK", "IKIRE MICROFINANCE BANK"),
                            ("ILISAN_MICROFINANCE_BANK", "ILISAN MICROFINANCE BANK"),
                            (
                                "IMO_STATE_MICROFINANCE_BANK",
                                "IMO STATE MICROFINANCE BANK",
                            ),
                            (
                                "IMPERIAL_HOMES_MORTGAGE_BANK",
                                "IMPERIAL HOMES MORTGAGE BANK",
                            ),
                            ("INFINITY_MFB", "Infinity MFB"),
                            (
                                "INFINITY_TRUST_MORTGAGE_BANK",
                                "INFINITY TRUST MORTGAGE BANK",
                            ),
                            ("INNOVECTIVES_KESH", "INNOVECTIVES KESH"),
                            ("INTELLFIN", "INTELLFIN"),
                            (
                                "INTERLAND_MICROFINANCE_BANK",
                                "INTERLAND MICROFINANCE BANK",
                            ),
                            ("IRL_MICROFINANCE_BANK", "IRL MICROFINANCE BANK"),
                            (
                                "ISALEOYO_MICROFINANCE_BANK",
                                "ISALEOYO MICROFINANCE BANK",
                            ),
                            ("JAIZ_BANK", "JAIZ BANK"),
                            ("JUBILEE_LIFE", "JUBILEE LIFE"),
                            ("KEYSTONE_BANK", "Keystone bank"),
                            (
                                "KONTAGORA_MICROFINANCE_BANK",
                                "KONTAGORA MICROFINANCE BANK",
                            ),
                            ("KUDA_MICROFINANCE_BANK", "Kuda Microfinance Bank"),
                            (
                                "LAGOS_BUILDING_AND_INVESTMENT_COMPANY",
                                "LAGOS BUILDING AND INVESTMENT COMPANY",
                            ),
                            (
                                "LAGOS_BUILDING_INVESTMENT_COMPANY_PLC",
                                "Lagos Building Investment Company Plc.",
                            ),
                            ("LAPO_MICROFINANCE_BANK", "LAPO MICROFINANCE BANK"),
                            (
                                "LAVENDER_MICROFINANCE_BANK",
                                "LAVENDER MICROFINANCE BANK",
                            ),
                            ("LEGEND_MICROFINANCE_BANK", "LEGEND MICROFINANCE BANK"),
                            (
                                "MAINSTREET_MICROFINANCE_BANK",
                                "MAINSTREET MICROFINANCE BANK",
                            ),
                            ("MANNY_MICROFINANCE_BANK", "MANNY MICROFINANCE BANK"),
                            ("MAYFAIR_MICROFINANCE_BANK", "MAYFAIR MICROFINANCE BANK"),
                            ("MAYFRESH_MORTGAGE_BANK", "MAYFRESH MORTGAGE BANK"),
                            (
                                "MEGAPRAISE_MICROFINANCE_BANK",
                                "MEGAPRAISE MICROFINANCE BANK",
                            ),
                            (
                                "MICROCRED_MICROFINANCE_BANK",
                                "MICROCRED MICROFINANCE BANK",
                            ),
                            (
                                "MICROVIS_MICROFINANCE_BANK",
                                "MICROVIS MICROFINANCE BANK",
                            ),
                            ("MINT_FINEX_MFB", "MINT-FINEX MFB"),
                            ("MOLUSI_MICROFINANCE_BANK", "MOLUSI MICROFINANCE BANK"),
                            ("MONEY_BOX", "MONEY BOX"),
                            (
                                "MONEY_TRUST_MICROFINANCE_BANK",
                                "MONEY TRUST MICROFINANCE BANK",
                            ),
                            ("MOZFIN_MICROFINANCE_BANK", "MOZFIN MICROFINANCE BANK"),
                            (
                                "MUTUAL_TRUST_MICROFINANCE_BANK",
                                "MUTUAL TRUST MICROFINANCE BANK",
                            ),
                            ("NDIORAH_MICROFINANCE_BANK", "NDIORAH MICROFINANCE BANK"),
                            ("NEPTUNE_MICROFINANCE_BANK", "NEPTUNE MICROFINANCE BANK"),
                            (
                                "NEW_DAWN_MICROFINANCE_BANK",
                                "NEW DAWN MICROFINANCE BANK",
                            ),
                            (
                                "NEW_GOLDEN_PASTURES_MICROFINANCE_BANK",
                                "NEW GOLDEN PASTURES MICROFINANCE BANK",
                            ),
                            (
                                "NIGERIAN_NAVY_MICROFINANCE_BANK",
                                "NIGERIAN NAVY MICROFINANCE BANK",
                            ),
                            (
                                "NIRSAL_NATIONAL_MICROFINANCE_BANK",
                                "NIRSAL NATIONAL MICROFINANCE BANK",
                            ),
                            (
                                "NNEW_WOMEN_MICROFINANCE_BANK",
                                "NNEW WOMEN MICROFINANCE BANK",
                            ),
                            ("NOVA_MERCHANT_BANK", "NOVA MERCHANT BANK"),
                            ("NPF_MICROFINANCE_BANK", "NPF MICROFINANCE BANK"),
                            ("NUTURE_MICROFINANCE_BANK", "NUTURE MICROFINANCE BANK"),
                            (
                                "NWANNEGADI_MICROFINANCE_BANK",
                                "NWANNEGADI MICROFINANCE BANK",
                            ),
                            ("OCHE_MICROFINANCE_BANK", "OCHE MICROFINANCE BANK"),
                            ("OHAFIA_MICROFINANCE_BANK", "OHAFIA MICROFINANCE BANK"),
                            ("OKPOGA_MICROFINANCE_BANK", "OKPOGA MICROFINANCE BANK"),
                            (
                                "OLABISI_ONABANJO_UNIVERSITY_MICROFINANCE",
                                "OLABISI ONABANJO UNIVERSITY MICROFINANCE",
                            ),
                            ("OMIYE_MICROFINANCE_BANK", "OMIYE MICROFINANCE BANK"),
                            ("OMOLUABI", "OMOLUABI"),
                            ("ONE_FINANCE", "ONE FINANCE"),
                            ("OPAY", "OPAY"),
                            ("PAGA", "PAGA"),
                            ("PAGE_MFBANK", "PAGE MFBank"),
                            ("PALMPAY", "PALMPAY"),
                            ("PARALLEX", "PARALLEX"),
                            ("PARKWAY_READYCASH", "PARKWAY-READYCASH"),
                            (
                                "PATRICKGOLD_MICROFINANCE_BANK",
                                "PATRICKGOLD MICROFINANCE BANK",
                            ),
                            ("PAYATTITUDE_ONLINE", "PAYATTITUDE ONLINE"),
                            ("PAYSTACK_PAYMENTS_LIMITED", "PAYSTACK PAYMENTS LIMITED"),
                            (
                                "PECANTRUST_MICROFINANCE_BANK",
                                "PECANTRUST MICROFINANCE BANK",
                            ),
                            (
                                "PENNYWISE_MICROFINANCE_BANK",
                                "PENNYWISE MICROFINANCE BANK",
                            ),
                            (
                                "PERSONAL_TRUST_MICROFINANCE_BANK",
                                "PERSONAL TRUST MICROFINANCE BANK",
                            ),
                            ("PETRA_MICROFINANCE_BANK", "Petra Microfinance Bank Plc"),
                            ("PILLAR_MICROFINANCE_BANK", "PILLAR MICROFINANCE BANK"),
                            ("PLATINUM_MORTGAGE_BANK", "PLATINUM MORTGAGE BANK"),
                            ("POLARIS_BANK", "Polaris Bank"),
                            (
                                "POLYUNWANA_MICROFINANCE_BANK",
                                "POLYUNWANA MICROFINANCE BANK",
                            ),
                            (
                                "PRESTIGE_MICROFINANCE_BANK",
                                "PRESTIGE MICROFINANCE BANK",
                            ),
                            ("PROVIDUS_BANK", "Providus Bank"),
                            (
                                "PURPLEMONEY_MICROFINANCE_BANK",
                                "PURPLEMONEY MICROFINANCE BANK",
                            ),
                            (
                                "QUICKFUND_MICROFINANCE_BANK",
                                "QUICKFUND MICROFINANCE BANK",
                            ),
                            ("RAND_MERCHANT_BANK", "RAND MERCHANT BANK"),
                            ("REFUGE_MORTGAGE_BANK", "REFUGE MORTGAGE BANK"),
                            ("REGENT_MICROFINANCE_BANK", "REGENT MICROFINANCE BANK"),
                            (
                                "RENMONEY_MICROFINANCE_BANK",
                                "RENMONEY MICROFINANCE BANK",
                            ),
                            (
                                "REPHIDIM_MICROFINANCE_BANK",
                                "REPHIDIM MICROFINANCE BANK",
                            ),
                            ("RICHWAY_MICROFINANCE_BANK", "RICHWAY MICROFINANCE BANK"),
                            ("ROLEZ_MICROFINANCE_BANK", "Rolez Microfinance Bank"),
                            (
                                "ROYAL_EXCHANGE_MICROFINANCE_BANK",
                                "ROYAL EXCHANGE MICROFINANCE BANK",
                            ),
                            ("RUBIES_MICROFINANCE_BANK", "Rubies Micro-finance Bank"),
                            (
                                "SAFE_HAVEN_MICROFINANCE_BANK",
                                "SAFE HAVEN MICROFINANCE BANK",
                            ),
                            ("SAFETRUST", "SAFETRUST"),
                            ("SAGAMU_MICROFINANCE_BANK", "SAGAMU MICROFINANCE BANK"),
                            (
                                "SEED_CAPITAL_MICROFINANCE_BANK",
                                "SEED CAPITAL MICROFINANCE BANK",
                            ),
                            (
                                "SEEDVEST_MICROFINANCE_BANK",
                                "SEEDVEST MICROFINANCE BANK",
                            ),
                            ("SPARKLE_MICROFINANCE_BANK", "Sparkle Microfinance Bank"),
                            ("STANBIC_IBTC_EASE_WALLET", "STANBIC IBTC @Ease WALLET"),
                            ("STANBIC_IBTC_BANK", "Stanbic IBTC Bank Ltd."),
                            (
                                "STANDARD_CHARTERED_BANK",
                                "Standard Chartered Bank Nigeria Ltd.",
                            ),
                            ("STELLAS_MICROFINANCE_BANK", "STELLAS MICROFINANCE BANK"),
                            ("STERLING_BANK", "Sterling Bank"),
                            ("STERLING_MOBILE", "STERLING MOBILE"),
                            ("SULSPAP_MICROFINANCE_BANK", "SULSPAP MICROFINANCE BANK"),
                            ("SUNTRUST_BANK", "Suntrust Bank Nigeria Limited"),
                            ("TAGPAY", "TAGPAY"),
                            ("TAJ_BANK", "Taj Bank"),
                            ("TCF_MFB", "TCF MFB"),
                            ("TEASY_MOBILE", "TEASY MOBILE"),
                            (
                                "THINK_FINANCE_MICROFINANCE_BANK",
                                "THINK FINANCE MICROFINANCE BANK",
                            ),
                            ("TITAN_BANK", "Titan Bank"),
                            ("TRIDENT_MICROFINANCE_BANK", "TRIDENT MICROFINANCE BANK"),
                            ("TRUST_MICROFINANCE_BANK", "TRUST MICROFINANCE BANK"),
                            (
                                "TRUSTBANC_J6_MICROFINANCE_BANK",
                                "TRUSTBANC J6 MICROFINANCE BANK LIMITED",
                            ),
                            (
                                "TRUSTFUND_MICROFINANCE_BANK",
                                "TRUSTFUND MICROFINANCE BANK",
                            ),
                            ("U_C_MICROFINANCE_BANK", "U & C MICROFINANCE BANK"),
                            ("UNAAB_MICROFINANCE_BANK", "UNAAB MICROFINANCE BANK"),
                            ("UNICAL_MICROFINANCE_BANK", "Unical Microfinance Bank"),
                            ("UNION_BANK", "Union Bank"),
                            ("UBA", "United Bank For Africa Plc"),
                            ("UNITY_BANK", "Unity Bank Plc"),
                            (
                                "UNN_MICROFINANCE_BANK",
                                "UNIVERSITY OF NIGERIA, NSUKKA MICROFINANCE BANK",
                            ),
                            (
                                "VENTURE_GARDEN_NIGERIA",
                                "VENTURE GARDEN NIGERIA LIMITED",
                            ),
                            ("VFD_MICROFINANCE_BANK", "VFD Microfinance Bank"),
                            ("VIRTUE_MICROFINANCE_BANK", "VIRTUE MICROFINANCE BANK"),
                            ("VISA_MICROFINANCE_BANK", "VISA MICROFINANCE BANK"),
                            ("VT_NETWORKS", "VT NETWORKS"),
                            ("WEMA_BANK", "Wema Bank"),
                            ("WETLAND_MICROFINANCE_BANK", "WETLAND MICROFINANCE BANK"),
                            ("XSLNCE_MICROFINANCE_BANK", "XSLNCE MICROFINANCE BANK"),
                            ("YES_MICROFINANCE_BANK", "YES MICROFINANCE BANK"),
                            ("YOBE_MICROFINANCE_BANK", "YOBE MICROFINANCE BANK"),
                            ("ZENITH_BANK", "Zenith Bank"),
                            ("ZENITH_MOBILE", "ZENITH MOBILE"),
                            ("ZINTERNET_KONGAPA", "ZINTERNET - KONGAPA"),
                        ],
                        max_length=200,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="UserEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("affiliate_institution", models.CharField(blank=True, max_length=300)),
                ("department", models.CharField(blank=True, max_length=300)),
                ("country", models.CharField(blank=True, max_length=300)),
                ("state", models.CharField(blank=True, max_length=300)),
                ("city", models.CharField(blank=True, max_length=300)),
                ("address", models.CharField(blank=True, max_length=300)),
                (
                    "participant_type",
                    models.CharField(
                        choices=[("Physical", "Physical"), ("Virtual", "Virtual")],
                        max_length=300,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateField(auto_now_add=True)),
                (
                    "receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.paymentreceipt",
                    ),
                ),
            ],
        ),
    ]
