# Generated by Django 4.1.4 on 2022-12-31 23:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearancefile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clearancefile',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
    ]
