# Generated by Django 4.1.4 on 2024-11-23 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("event", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userevent",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="receiptverificationlogs",
            name="receipt",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_log",
                to="event.paymentreceipt",
            ),
        ),
        migrations.AddField(
            model_name="receiptverificationlogs",
            name="verified_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="clearancefile",
            name="receipt",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="event.paymentreceipt"
            ),
        ),
        migrations.AddField(
            model_name="clearancefile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="abstract",
            name="receipt",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="event.paymentreceipt"
            ),
        ),
        migrations.AddField(
            model_name="abstract",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="receiptverificationlogs",
            constraint=models.UniqueConstraint(
                fields=("transaction_id", "payment_bank"),
                name="transaction_id_unique_with_payment_bank",
            ),
        ),
    ]
