# Generated by Django 4.1.4 on 2024-11-30 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("event", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentreceipt",
            name="verification_log",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reciept",
                to="event.receiptverificationlogs",
            ),
        ),
        migrations.AlterField(
            model_name="receiptverificationlogs",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
