# Generated by Django 4.1.4 on 2024-11-23 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("event", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                (
                    "attachment",
                    models.FileField(null=True, upload_to="uploads/contactus/"),
                ),
                ("resolved", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("resolution_date", models.DateTimeField(null=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
