# Generated by Django 4.1.4 on 2025-02-12 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_paymentreceipt_verification_log_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearancefile',
            name='submission_type',
            field=models.CharField(choices=[('Event Registration', 'Event Registration'), ('Manuscript', 'Manuscript'), ('Exhibition', 'Exhibition'), ('Advert', 'Advert')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='receipt',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.paymentreceipt'),
        ),
    ]
