# Generated by Django 4.1.4 on 2023-01-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_abstract_abstract_document_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearancefile',
            name='submission_file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
