# Generated by Django 4.1.4 on 2023-01-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_clearancefile_submission_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='abstract_document_file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
