# Generated by Django 4.1.4 on 2025-03-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_userevent_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptverificationlogs',
            name='verified_by',
        ),
        migrations.RemoveConstraint(
            model_name='paymentreceipt',
            name='failure_reason required for `Failed verification` status',
        ),
        migrations.RemoveConstraint(
            model_name='paymentreceipt',
            name='verification_log requireed for `Verified` status',
        ),
        migrations.RemoveField(
            model_name='paymentreceipt',
            name='verification_log',
        ),
        migrations.AddConstraint(
            model_name='paymentreceipt',
            constraint=models.CheckConstraint(check=models.Q(('failure_reason', ''), ('status', 2), _negated=True), name='failure_reason required for `Failed verification` status', violation_error_message='Please add a failure reason when marking a payment receipt status as `Failed verification`'),
        ),
        migrations.DeleteModel(
            name='ReceiptVerificationLogs',
        ),
    ]
