# Generated by Django 4.1.4 on 2023-02-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_abstract_coresponding_author_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='research_area',
            field=models.CharField(choices=[('Bio', 'Biotechnology, Bioinformatics and Cheminformatics'), ('Medicine', 'Medicinal plants and drug development'), ('Conservation', 'Conservation and utilization of our natural heritage/ resources'), ('Energy', 'Energy and Mineral Resources'), ('Environmental', 'Environmental Pollution and Remediation'), ('Science', 'Science and security'), ('IT', 'Information technology'), ('Agriculture', 'Agriculture and Food Security'), ('Nanotech', 'Nanotechnology'), ('Computational', 'Computational/Mathematical modeling'), ('Aquaculture', 'Aquaculture and the Blue Economy '), ('Health', 'Climatic change and human health'), ('Nanotechnology', 'Nanotechnology')], max_length=200),
        ),
    ]
