# Generated by Django 4.1.4 on 2025-03-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_abstract_receipt_alter_clearancefile_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='user_notified',
            field=models.BooleanField(default=False),
        ),
    ]
