# Generated by Django 4.1.4 on 2023-02-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_abstract_research_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='research_area',
            field=models.CharField(max_length=200),
        ),
    ]
