# Generated by Django 4.1.4 on 2023-03-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_abstract_research_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='abstract_document_file',
            field=models.FileField(max_length=500, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='clearancefile',
            name='evidence_of_payment_file',
            field=models.FileField(max_length=500, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='clearancefile',
            name='submission_file',
            field=models.FileField(max_length=500, null=True, upload_to='uploads/'),
        ),
    ]
