version: '3.9'

services:
  backend:
    build:
      context: ./backend/
    restart: on-failure
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    command: >
      sh -c "
        python manage.py migrate --noinput &&
        python manage.py collectstatic --noinput &&
        python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env

  frontend:
    build:
      context: ./frontend/
    restart: on-failure
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    command: >
      sh -c "npm start"
    env_file:
      - ./.env
    depends_on:
      - backend

volumes:
  pgdata: {}