version: '3.9'

services:
  db:
    image: postgres:14
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432"
    env_file:
      - ./.env
    restart: on-failure

  backend:
    build:
      context: .
    restart: on-failure
    ports:
      - "8000:8000"
    volumes:
      - .:/backend
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  redis:
    image: redis:alpine
    restart: always

  celery:
    restart: always
    build:
      context: .
    command: celery -A conference worker -l info
    volumes:
      - .:/backend
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - backend

volumes:
  pgdata: {}