version: '3.9'

services:
  db:
    image: postgres:14
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432"
    env_file:
      - ./.env
    restart: on-failure

  backend:
    build:
      context: ./backend/
    restart: on-failure
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    command: >
      sh -c "
        python manage.py migrate --noinput &&
        python manage.py collectstatic --noinput &&
        python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/
    restart: on-failure
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    command: >
      sh -c "npm start"
    env_file:
      - ./.env
    depends_on:
      - backend

  redis:
    image: redis:alpine
    restart: always

  celery:
    restart: always
    build:
      context: ./backend/
    command: celery -A conference worker -l info
    volumes:
      - ./backend:/backend
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - backend

volumes:
  pgdata: {}