# Generated by Django 4.1.4 on 2024-11-30 12:22

from django.db import migrations
import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user.user",),
            managers=[
                ("objects", user.models.UserManager()),
            ],
        ),
    ]
