# Generated by Django 4.1.4 on 2022-12-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('coresponding_author_fullname', models.CharField(max_length=200)),
                ('coresponding_author_email', models.EmailField(blank=True, max_length=140)),
                ('coresponding_author_phone', models.CharField(blank=True, max_length=140)),
                ('abstract_document_file', models.FileField(blank=True, editable=False, upload_to='uploads/')),
                ('presentation_type', models.CharField(choices=[('oral', 'Live oral'), ('virtual', 'Live Virtual'), ('poster', 'Poster')], max_length=100)),
                ('research_area', models.CharField(choices=[('Bio', 'Biotechnology, Bioinformatics and Cheminformatics'), ('Medicine', 'Medicinal plants and drug development'), ('Conservation', 'Conservation and utilization of our natural heritage/ resources'), ('Energy', 'Energy and Mineral Resources'), ('Environmental', 'Environmental Pollution and Remediation'), ('Science', 'Science and security'), ('IT', 'Information technology'), ('Agriculture', 'Agriculture and Food Security'), ('Nanotech', 'Nanotechnology'), ('Computational', 'Computational/Mathematical modeling'), ('Aquaculture', 'Aquaculture and the Blue Economy '), ('Health', 'Climatic change and human health')], max_length=200)),
                ('keywords', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClearanceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('submission_type', models.CharField(choices=[('Manuscript', 'Manuscript'), ('Exhibition', 'Exhibition'), ('Advert', 'Advert')], max_length=20)),
                ('evidence_of_payment_file', models.FileField(upload_to='uploads/')),
                ('submission_file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
