# Generated by Django 4.1.4 on 2022-12-17 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('coresponding_author_email', models.EmailField(blank=True, max_length=140)),
                ('co_authors', models.TextField()),
                ('abstract_document_file', models.FileField(blank=True, editable=False, upload_to='uploads/')),
                ('abstract_text', models.TextField(blank=True)),
                ('research_area', models.CharField(default=None, max_length=999)),
                ('keywords', models.CharField(max_length=200)),
                ('coresponding_author_phone', models.CharField(default=0, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=200)),
                ('event_datetime', models.DateField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='EventPaymentLog',
            fields=[
                ('user_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event.event')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now_add=True)),
                ('payment_datetime', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Not verified', 'Not verified')], max_length=100)),
                ('receipt', models.FileField(blank=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now_add=True)),
                ('submitted', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
    ]
