# Generated by Django 4.1.4 on 2022-12-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=250)),
                ('topic', models.CharField(choices=[('Bio', 'Biotechnology'), ('Medicine', 'Medicinal plants and drug development'), ('Conservation', 'Conservation and utilization of our natural heritage'), ('Energy', 'Energy and Mineral Resources'), ('Environmental', 'Environmental Pollution and Remediation'), ('Science', 'Science and security'), ('IT', 'Information technology'), ('Agriculture', 'Agriculture and Food Security'), ('Nanotech', 'Nanotechnology'), ('Computational', 'Computational/Mathematical modeling'), ('Aquaculture', 'Aquaculture and the Blue Economy ')], max_length=100)),
                ('abstract', models.FileField(blank=True, upload_to='uploads/')),
                ('submitted', models.DateField(auto_now_add=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=140)),
                ('co_authors', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
