# Generated by Django 3.2.8 on 2022-12-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='abstract',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
