# Generated by Django 4.1.4 on 2023-01-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_clearancefile_created_at_alter_clearancefile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearancefile',
            name='submission_file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
