# Generated by Django 3.2.8 on 2022-12-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_abstract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='event',
            name='co_authors',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
