# Generated by Django 4.1.4 on 2022-12-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_rename_created_at_event_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
