# Generated by Django 4.1.4 on 2022-12-17 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevent',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='submitted',
        ),
    ]
