# Generated by Django 4.1.4 on 2022-12-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevent',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='submitted',
        ),
        migrations.AlterField(
            model_name='abstract',
            name='co_authors',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='keywords',
            field=models.JSONField(default=list),
        ),
    ]
