# Generated by Django 4.1.4 on 2022-12-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_abstract_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='co_authors',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='keywords',
            field=models.JSONField(default=list),
        ),
    ]
