# Generated by Django 3.2.8 on 2022-12-13 16:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0003_auto_20221210_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Co_Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('institution', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='event',
            name='author',
        ),
        migrations.RemoveField(
            model_name='event',
            name='co_authors',
        ),
        migrations.RemoveField(
            model_name='event',
            name='email',
        ),
        migrations.RemoveField(
            model_name='event',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='event',
            name='submitted',
        ),
        migrations.RemoveField(
            model_name='event',
            name='topic',
        ),
        migrations.AddField(
            model_name='event',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 12, 13, 16, 2, 30, 110447, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='date_updated',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 12, 13, 16, 2, 36, 341514, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='event_datetime',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 12, 13, 16, 2, 42, 424849, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now_add=True)),
                ('submitted', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventPaymentLog',
            fields=[
                ('user_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event.event')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now_add=True)),
                ('payment_datetime', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Not verified', 'Not verified')], max_length=100)),
                ('receipt', models.FileField(blank=True, upload_to='uploads/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_email', models.EmailField(max_length=254, verbose_name=models.EmailField(blank=True, max_length=140))),
                ('keywords', models.CharField(choices=[('Bio', 'Biotechnology'), ('Medicine', 'Medicinal plants and drug development'), ('Conservation', 'Conservation and utilization of our natural heritage'), ('Energy', 'Energy and Mineral Resources'), ('Environmental', 'Environmental Pollution and Remediation'), ('Science', 'Science and security'), ('IT', 'Information technology'), ('Agriculture', 'Agriculture and Food Security'), ('Nanotech', 'Nanotechnology'), ('Computational', 'Computational/Mathematical modeling'), ('Aquaculture', 'Aquaculture and the Blue Economy ')], max_length=100)),
                ('abstract', models.FileField(blank=True, editable=False, upload_to='uploads/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('co_authors', models.ManyToManyField(to='event.Co_Author')),
            ],
        ),
    ]
