# Generated by Django 3.2.8 on 2022-12-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20221213_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='author_email',
            field=models.EmailField(blank=True, max_length=140),
        ),
    ]
