# Generated by Django 3.2.8 on 2022-12-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_abstract_author_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('institution', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Co_Author',
        ),
        migrations.AlterField(
            model_name='abstract',
            name='co_authors',
            field=models.ManyToManyField(to='event.CoAuthor'),
        ),
    ]
