# Generated by Django 4.1.4 on 2022-12-17 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20221213_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='other_names',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
